import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; // 引入全局样式
import { AuthProvider } from "@/context/AuthContext"; // 用户上下文
import { ProjectProvider } from "@/context/ProjectContext"; // 项目上下文
import { DiscussionsProvider } from '@/context/DiscussionsContext';
import Layout from "@/components/shared/Layout"; // 引入共享布局组件

// 字体加载
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// 页面元数据
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 根布局组件
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProjectProvider>
            <DiscussionsProvider>
            <Layout>
              {children} {/* 子页面内容 */}
            </Layout>
            </DiscussionsProvider>
            {/* 底部栏 */}
            <footer className="bg-white shadow-md text-center py-4">
              &copy; {new Date().getFullYear()} TranslateOS. All rights reserved.
            </footer>
          </ProjectProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
