import { Metadata } from 'next';
import { AuthProvider } from '@/context/AuthContext';
import { ProjectProvider } from '@/context/ProjectContext';
import { DiscussionsProvider } from '@/context/DiscussionsContext';
import Layout from '@/components/shared/Layout'; // 引入共享布局
import { ThemeProvider } from '@/context/ThemeContext';

// 页面元数据 (只能在服务器端定义)
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayoutServer({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <meta charSet="UTF-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
                <title>TranslateOS</title>
            </head>
            <body>
                <ThemeProvider>
                    <AuthProvider>
                        <ProjectProvider>
                            <DiscussionsProvider>
                                {children}
                            </DiscussionsProvider>
                        </ProjectProvider>
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
